# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# 多语言配置
en:
  languageName: English
  weight: 1
  contentDir: content
  title: Antifragile Prompting (AFP) Framework
  params:
    description: "Antifragile Prompting (AFP) Framework · SafeLoop whitepaper and skeleton"  
  menu:
    main: main

zh:
  languageName: 中文
  weight: 2
  contentDir: content
  title: 抗脆弱提示框架（AFP）
  params:
    description: "抗脆弱白皮书与提示框架（AFP）· Antifragile Prompting (AFP) Framework · SafeLoop"
  menu:
    main: main.zh


  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
