main:
  - name: Home
    url: /
    weight: 10
  - name: Specification
    url: /specification/
    weight: 20
  - name: Evaluations
    url: /evaluations/
    weight: 30
  - name: Failure Cases
    url: /failure-cases/
    weight: 40
  - name: System Prompt
    url: /post/2025-09-10-afp-basic-framework/
    weight: 50
  - name: Whitepaper
    url: /publication/
    weight: 60
  - name: License
    url: /license/
    weight: 90
