# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: emerald

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Antifragile Prompting (AFP) Framework · SafeLoop'
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "Antifragile Prompting (AFP)"

# Site footer
footer:
  copyright:
    notice: '© {year} Me. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false

homepage:
  sections:
    - hero
    - about
    - people_founder
    - publication

blocks:
  about:
    show_avatar: false

blocks:
  people_founder:
    title: "Founder"
    subtitle: ""
    type: "people"          # 使用内建 People 积木
    content:
      users: ["admin"]      # 只显示 admin 这位作者
      show_social: true
      show_interests: false
    design:
      columns: 1
      avatar_shape: "circle"
      avatar_size: "sm"     # 〔假设〕支持 xs/sm/md/lg;不支持时会退回默认

