# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: emerald

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Antifragile Prompting (AFP) Framework · SafeLoop'
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      image: "afp-logo.png"    # 放在 assets/media/ 里
      text: "Antifragile Prompting (AFP)"

# Site footer
footer:
  block: minimal
  copyright:
    # 页脚一句话；{year} 自动显示年份；{license} 自动变成许可证链接
    notice: "© {year} CHING HUI KAI · Antifragile Prompting (AFP). This work is licensed under {license}."
    # 选择 CC 授权（HugoBlox 会依据这些选项生成 {license} 链接）
    license:
      enable: true
      allow_derivatives: true     # 允许演绎（CC BY 允许）
      share_alike: false          # 非 SA
      allow_commercial: true      # 允许商用（CC BY 允许）

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false

homepage:
  sections:
    - hero
    - about
    - people_founder
    - publication

blocks:
  about:
    show_avatar: false
    actions:
      - label: "Download Whitepaper"
        url: "/uploads/afp-whitepaper.pdf"
        icon: download

blocks:
  people_founder:
    title: "Founder"
    subtitle: ""
    type: "people"          # 使用内建 People 积木
    content:
      users: ["admin"]      # 只显示 admin 这位作者
      show_social: true
      show_interests: false
    design:
      columns: 1
      avatar_shape: "circle"
      avatar_size: "sm"     # 〔假设〕支持 xs/sm/md/lg;不支持时会退回默认

